[workspace]
members = [".", "plugin-sdk", "driver-postgres", "driver-mysql", "driver-mssql", "driver-sqlite"]
resolver = "2"

[package]
name = "tablepro-windows"
version = "0.2.0"
edition = "2021"

[lib]
name = "tablepro_windows"
crate-type = ["rlib"]

[[bin]]
name = "tablepro-windows"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "time"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "5"
tablepro-plugin-sdk = { path = "plugin-sdk" }
libloading = "0.8"
async-trait = "0.1"
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-updater = "2"
rusqlite = { version = "0.32", features = ["bundled"] }
rust_xlsxwriter = "0.79"
flate2 = "1"
russh = "0.45"
russh-keys = "0.45"
base64 = "0.22"

[target.'cfg(windows)'.dependencies]
windows-dpapi = "0.2"

[features]
devtools = ["tauri/devtools"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[dev-dependencies]
tempfile = "3"
