[package]
name = "driver-mysql"
version = "0.1.0"
edition = "2021"

[dependencies]
driver-common = { path = "../driver-common" }
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
mysql_async = { version = "0.34", default-features = false, features = ["default-rustls"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }

[lib]
name = "driver_mysql"
crate-type = ["rlib"]
