[package]
name = "driver-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
driver-common = { path = "../driver-common" }
async-trait = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync"] }
rusqlite = { version = "0.32", features = ["bundled", "column_decltype"] }

[lib]
name = "driver_sqlite"
crate-type = ["rlib"]
